### ISSUE TITLE
Problema com títulos com : (dois pontos)

### ISSUE THREAD

**Issue by TroyeTroye** [Kartatz/UbookDLAndroid#1]
Olá.
Encontrei um app por acaso num grupo do Telegram com esse nome (UbookDL) e ele permite baixar arquivos do app oficial. Comecei a usar esses dias, porém notei que os arquivos cujos títulos contêm : (dois pontos), o Ubook DL não consegue baixar. Não sei se isso já foi notado antes, e não sei se esse repository tem relação com o app, mas se tiver (tomara que tenha, não encontrei mais nada relacionado), queria pedir por favor se poderia verificar para que possa funcionar com os arquivos que contenham : (dois pontos), porque eu mesmo não entendo nada de programação rs. Obrigado.

**Comment by Kartatz** [comment]
Olá.

Eu parei de trabalhar nesse projeto, portanto não estou mais realizando correções ou adicionando coisas novas.

Além do mais, não possuo mais assinatura no Ubook.

Obrigado pela compreensão.
